-- MySQL Script generated by MySQL Workbench
-- Tue Nov 18 11:06:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gym` DEFAULT CHARACTER SET utf8 ;
USE `gym` ;




-- -----------------------------------------------------
-- Table `Course_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Course_types` (
  `course_type_id` INT NOT NULL,
  `course_type_name` VARCHAR(45) NULL,
  `active_flag` TINYINT(1) NULL,
  PRIMARY KEY (`course_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses` (
  `courses_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  `course_type_id` INT NOT NULL,
  `active_flag` TINYINT(1) NULL,
  PRIMARY KEY (`courses_id`),
  INDEX `fk_Courses_course_types1_idx` (`course_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_course_types1`
    FOREIGN KEY (`course_type_id`)
    REFERENCES `Course_types` (`course_type_id`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Categories` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NULL,
  `active_flag` TINYINT(1) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory` (
  `inventory_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `active_flag` TINYINT(1) NULL,
  `brand` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `description` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`inventory_id`),
  INDEX `fk_Inventory_Categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_Categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `Categories` (`category_id`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inventory_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inventory_logs` (
  `inventory_log_id` INT NOT NULL,
  `active_flag` TINYINT(1) NULL,
  `action_date` DATE NULL,
  `description` VARCHAR(45) NULL,
  `inventory_id` INT NOT NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`inventory_log_id`),
  INDEX `fk_Inventory_tracking_Inventory1_idx` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_tracking_Inventory1`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `Inventory` (`inventory_id`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gym_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gym_sessions` (
  `gym_session_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `courses_id` INT NOT NULL,
  `max_subscription` INT NULL,
  `current_subscription` INT NULL,
  `QR` VARCHAR(45) NULL,
  PRIMARY KEY (`gym_session_id`),
  INDEX `fk_Session_Courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Session_Courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `Courses` (`courses_id`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rooms` (
  `room_id` INT NOT NULL,
  `room_name` VARCHAR(255) NULL,
  `active_flag` TINYINT(1) NULL,
  `capacity` INT NULL,
  `length` FLOAT NULL,
  `width` FLOAT NULL,
  `height` FLOAT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accessories_reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accessories_reservation` (
  `accessory_reservation_id` INT NOT NULL,
  `date_from` DATETIME NULL,
  `date_to` DATETIME NULL,
  `creation_date` DATETIME NULL,
  `session_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`accessory_reservation_id`),
  INDEX `fk_Inventory_reservations_Session1_idx` (`session_id` ASC) VISIBLE,
  INDEX `fk_accessories_reservation_rooms1_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_Inventory_reservations_Session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `Gym_sessions` (`gym_session_id`)
    
    ,
  CONSTRAINT `fk_accessories_reservation_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `rooms` (`room_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Duration_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Duration_types` (
  `duration_type_id` INT NOT NULL,
  `Duration_type` VARCHAR(45) NULL,
  `active_flag` TINYINT(1) NULL,
  PRIMARY KEY (`duration_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subscription_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscription_types` (
  `subscription_type_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `duration_type_id` INT NOT NULL,
  `active_flag` TINYINT(1) NULL,
  `creation_date` DATE NULL,
  PRIMARY KEY (`subscription_type_id`),
  INDEX `fk_Subscription_types_Duration_types1_idx` (`duration_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_Subscription_types_Duration_types1`
    FOREIGN KEY (`duration_type_id`)
    REFERENCES `Duration_types` (`duration_type_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subscription_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscription_status` (
  `subscription_status_id` INT NOT NULL,
  `subscription_status` VARCHAR(45) NULL,
  `active_flag` VARCHAR(45) NULL,
  PRIMARY KEY (`subscription_status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subscription_histories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Subscription_histories` (
  `subscription_history_id` INT NOT NULL,
  `creation_date` DATE NULL,
  `date_from` DATE NULL,
  `date_to` DATE NULL,
  `next_due_date` DATE NULL,
  `active_flag` TINYINT(1) NULL,
  `subscription_type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `subscription_status_id` INT NOT NULL,
  PRIMARY KEY (`subscription_history_id`),
  INDEX `fk_subscription_histories_Subscription_types1_idx` (`subscription_type_id` ASC) VISIBLE,
  INDEX `fk_subscription_histories_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Subscription_histories_Subscription_status1_idx` (`subscription_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_histories_Subscription_types1`
    FOREIGN KEY (`subscription_type_id`)
    REFERENCES `Subscription_types` (`subscription_type_id`)
    
    ,
  CONSTRAINT `fk_subscription_histories_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    
    ,
  CONSTRAINT `fk_Subscription_histories_Subscription_status1`
    FOREIGN KEY (`subscription_status_id`)
    REFERENCES `Subscription_status` (`subscription_status_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Registrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Registrations` (
  `registration_id` INT NOT NULL,
  `creation_date` DATETIME NULL,
  `user_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`registration_id`),
  INDEX `fk_Registrations_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Registrations_Courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Registrations_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    
    ,
  CONSTRAINT `fk_Registrations_Courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `Courses` (`courses_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Presence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Presence` (
  `presence_id` INT NOT NULL,
  `creation_date` VARCHAR(45) NULL,
  `registration_id` INT NOT NULL,
  `comment` VARCHAR(45) NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`presence_id`),
  INDEX `fk_Presence_Registrations1_idx` (`registration_id` ASC) VISIBLE,
  INDEX `fk_Presence_Sessions1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_Presence_Registrations1`
    FOREIGN KEY (`registration_id`)
    REFERENCES `Registrations` (`registration_id`)
    
    ,
  CONSTRAINT `fk_Presence_Sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `Gym_sessions` (`gym_session_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Format_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Format_status` (
  `format_statut_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `active_flag` TINYINT(1) NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`format_statut_id`),
  INDEX `fk_Format_status_Courses1_idx` (`courses_id` ASC) VISIBLE,
  CONSTRAINT `fk_Format_status_Courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `Courses` (`courses_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Type_medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Type_medias` (
  `type_media_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `active_flag` TINYINT(1) NULL,
  PRIMARY KEY (`type_media_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Medias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Medias` (
  `media_id` INT NOT NULL,
  `active_flag` TINYINT(1) NULL,
  `description` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `type_media_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`media_id`),
  INDEX `fk_Medias_Type_medias1_idx` (`type_media_id` ASC) VISIBLE,
  INDEX `fk_Medias_Users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Medias_Type_medias1`
    FOREIGN KEY (`type_media_id`)
    REFERENCES `Type_medias` (`type_media_id`)
    
    ,
  CONSTRAINT `fk_Medias_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Invetory_trackings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Invetory_trackings` (
  `invetory_tracking_id` INT NOT NULL,
  `entry_date` DATE NULL,
  `room_id` INT NOT NULL,
  `inventory_id` INT NOT NULL,
  PRIMARY KEY (`invetory_tracking_id`),
  INDEX `fk_room_inventory_rooms1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_room_inventory_Inventory1_idx` (`inventory_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_inventory_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `rooms` (`room_id`)
    
    ,
  CONSTRAINT `fk_room_inventory_Inventory1`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `Inventory` (`inventory_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `settings` (
  `setting_id` INT NOT NULL,
  `company` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `horraires` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `contacts` VARCHAR(45) NULL,
  `social_link` VARCHAR(45) NULL,
  PRIMARY KEY (`setting_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subscription_pauses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subscription_pauses` (
  `subscription_pause_id` INT NOT NULL,
  `pause_date` DATE NULL,
  `due_date` DATE NULL,
  `subscription_history_id` INT NOT NULL,
  PRIMARY KEY (`subscription_pause_id`),
  INDEX `fk_subscription_pauses_Subscription_histories1_idx` (`subscription_history_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_pauses_Subscription_histories1`
    FOREIGN KEY (`subscription_history_id`)
    REFERENCES `Subscription_histories` (`subscription_history_id`)
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sessions_coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sessions_coach` (
  `session_coach_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  `active_flag` TINYINT(1) NULL,
  PRIMARY KEY (`session_coach_id`),
  INDEX `fk_Sessions_coach_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Sessions_coach_Sessions1_idx` (`session_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sessions_coach_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    
    ,
  CONSTRAINT `fk_Sessions_coach_Sessions1`
    FOREIGN KEY (`session_id`)
    REFERENCES `Gym_sessions` (`gym_session_id`)
    
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
